# fly.toml app configuration file generated for bnbscommunity on 2026-01-31T03:21:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bnbscommunity'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true

  # 改为 true，但配合 auto_stop_delay
  auto_stop_machines = true
  
  [[http_service.checks]]
    interval = "300s"  # 延长到5分钟
    timeout = "10s"
    grace_period = "20s"
    method = "GET"
    path = "/health"

