// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        android_gradle_plugin_version = '8.9.1'
        compile_sdk_version = 35
        target_sdk_version = 35
        min_sdk_version = 26
    }
    repositories {
        google()
        mavenCentral()  // 替换jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$android_gradle_plugin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()  // 替换jcenter()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}